### ISSUE TITLE
Exception on installation

### ISSUE THREAD

**Issue by dehlen** [MatthieuSegret/yummy-phoenix-graphql#1]
Hey,

first of all thanks for sharing this amazing project :) Your effort is really appreciated.
However I tried installing local instance on my machine and when running `mix run priv/repo/seeds.exs` I get the following exception:

`** (Arc.MissingExecutableError) Cannot locate executable: convert`.
I can attach the full log if it is of interest. Any idea what is going on there ? 

I am totally new to elixir and phoenix so I'm hoping this might be a simple fix.

**Comment by MatthieuSegret** [comment]
Hey,
Thank you for your support.
You need ImageMagick to run the project. I have just added it to [the prerequisites](https://github.com/MatthieuSegret/yummy-phoenix-graphql/commit/2215f6db9a9743f5e3cd3d77a60fc5636c7af571).

**Comment by dehlen** [comment]
Thanks, now it is working.
