### ISSUE TITLE
Nested mutations

### ISSUE THREAD

**Issue by dehlen** [MatthieuSegret/yummy-phoenix-graphql#4]
Hi,

I was wondering if you could help me implementing the following behavior: I added a new type similar to Comment called Nutrition. Nutrition is referenced with a recipe and has a one-to-one relationship.
Whenever a new recipe is created` (_NewRecipe)` i want to create a nutrition row in the nutrition table and link `nutrition_id` foreign key in the recipe already created recipe row.

Furthermore the nutrition information can be edited in the react-final-form already but I need help to update the nutrition information via a mutation on the backend side. So when a recipe is updated `(_EditRecipe)` the updated nutrition information should be persisted in the linked nutrition row (from `nutrition_id`). I think this could be achieved by modeling the nutrition mutation like the already existing comment mutations and somehow make a nested mutation` createNutrition { createRecipe { } } `in` _NewRecipe` or in `_EditRecipe`. 

What do you think ? I would really appreciate some help wrapping my head around this since this project involves a lot of technology. I am happy to contribute back if I can finish the nutrition implementation :)

**Comment by MatthieuSegret** [comment]
Hi,

I'm not sure I understand. Why do you talk about nested mutation with one-to-one relationship ?
Isn't it rather a one-to-many relationship between Nutrition and Recipe ? One recipe has many nutritions ?

**Comment by dehlen** [comment]
Ok let me try to elaborate. The recipe relation currently looks like this: 
| title | content | ... | user_id.

I added another relation called nutrition:
| calories | fat | protein | carbs | recipe_id | user_id

The recipe relation now has a new foreign_key called nutrition_id:
| title | content | ... | user_id | nutrition_id.

So one recipe has exactly one nutrition (this is what I meant with one-to-one relationship).
Currently in _NewRecipe.tsx there is a mutation createRecipe called which creates a recipe and adds the data into the database. I want to change the mutation (possibly by using nested mutations ?) in order to create the nutrition information and the recipe information with one call and link the foreign_keys respectively. So whenever a user enters information for a new recipe (or is editing one) with all the recipe data and nutrition data in the shown form the data is correctly persisted in the Postgres db.

**Comment by MatthieuSegret** [comment]
I better understand. You can implement one mutation to update `recipe` and `nutrition`:

`updateRecipeAndNutrition(
  recipe: {
    id: $id
    title: $title
    content: $content
    ...
  },
  nutrition: {
    id: $id
    calories: $calories
    protein: $protein
    ...
  }
) {...}`

In the resolver you can get the `recipe` and the `nutrition`, then update them in a single database transaction:

```
resolve fn (%{recipe: recipe_params, nutrition: nutrition_params}, _) ->
    recipe = Recipe |> Repo.get!(recipe_params[:id])
    nutrition = Nutrition |> Repo.get!(nutrition_params[:id])

    # Use Mutli Ecto module to perform this changes in a transaction
    # Update recipe with recipe_params
    # Update nutrition with nutrition_params
    # Run the transaction with Mutli
end
```

Unfortunately, I don't know Multi module. I advice you read Multi documentation : https://hexdocs.pm/ecto/Ecto.Multi.html

**Comment by dehlen** [comment]
Hey, thank you very much. This helps me quite a lot :)

**Comment by dehlen** [comment]
I'll close this because this guides me into the right direction. If I get a working implementation I am happy to share the changes if you are interested :)

**Comment by dehlen** [comment]
I got it working and I thought I'd share my findings.

I am using multi ecto now just as you proposed and it works like a charm. Thanks again :)

```elixir
def create(user, recipe, nutrition) do
    case Multi.new
      |> Multi.insert(:recipe, recipe_changeset(user, recipe))
      |> Multi.run(:nutrition, fn %{recipe: recipe} ->
          nutrition_changeset(user, recipe, nutrition) |> Repo.insert()
        end
      )
      |> Repo.transaction() do
      {:ok, %{recipe: recipe}} ->
        {:ok, recipe}
      {:error, :nutrition, changeset, _errors} ->
        {:error, changeset}
      {:error, :recipe, changeset, _errors} ->
        {:error, changeset}
    end
  end

  def recipe_changeset(user, recipe) do
    %Recipe{} 
      |> Recipe.changeset(recipe) 
      |> put_assoc(:author, user)
  end

  def nutrition_changeset(user, recipe, attrs) do
    %Nutrition{}
      |> Nutrition.changeset(attrs)
      |> put_assoc(:author, user)
      |> put_assoc(:recipe, recipe)
  end
```
